import Link from 'next/link';
import { features } from '@/lib/infogiph-home-content';
import { FeatureDemo } from './feature-demo';
import {
  LayersIcon,
  PlayIcon,
  ShareIcon,
  SparkleIcon,
  TypeIcon,
  VideoIcon,
} from './icons';
import type { FeatureCard } from './types';

const iconMap = {
  sparkle: SparkleIcon,
  type: TypeIcon,
  video: VideoIcon,
  layers: LayersIcon,
  play: PlayIcon,
  share: ShareIcon,
} as const;

function Card({ f }: { f: FeatureCard }) {
  const Icon = iconMap[f.icon];
  return (
    <Link
      href={f.href}
      className="group bg-card rounded-2xl border overflow-hidden flex flex-col hover:shadow-md transition-shadow"
    >
      <div className="relative aspect-[16/10] w-full bg-muted overflow-hidden">
        <FeatureDemo demo={f.demo} />
      </div>
      <div className="p-5 flex flex-col gap-3">
        <div className="flex items-center gap-2.5">
          <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-[#fafafa] border border-border text-foreground">
            <Icon className="h-4 w-4" />
          </span>
          <h4 className="font-semibold text-base sm:text-lg">{f.title}</h4>
        </div>
        <p className="text-sm text-muted-foreground leading-relaxed">
          {f.description}
        </p>
        {f.tags?.length ? (
          <div className="flex flex-wrap gap-1.5 mt-1">
            {f.tags.slice(0, 3).map((t) => (
              <span
                key={t}
                className="inline-flex items-center rounded-full bg-[#f5f5f5] px-2.5 py-1 text-[11px] sm:text-xs text-foreground/70"
              >
                {t}
              </span>
            ))}
          </div>
        ) : null}
      </div>
    </Link>
  );
}

export function Features() {
  return (
    <section className="mx-auto max-w-7xl px-4 sm:px-6 py-12 sm:py-24">
      <div className="mb-16 sm:mb-24">
        <h3 className="text-xl sm:text-3xl font-bold text-center mb-3">
          Everything you need for AI-powered infographics
        </h3>
        <p className="text-center text-muted-foreground mb-8 sm:mb-12 text-sm">
          From architecture diagrams to animated org charts — all generated by
          AI
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {features.map((f) => (
            <Card key={f.title} f={f} />
          ))}
        </div>
      </div>
    </section>
  );
}
